### DISCUSSION TITLE
Patch version overlooked or not being incremented properly

### DISCUSSION THREAD

**Discussion by DaneDH** [PaulHatch/semantic-version#164] [General]
If say my latest tag is `v0.17.0-beta`

The configuration below is giving me `0.16.0-beta` output when I have no `(MAJOR)` or `(MINOR)` in commit message. I am expecting to see `0.17.1-beta`. If I set `bump_each_commit: false`, I get something like `0.17.55-beta`. My expectation is that if no major or minor patterns are matched it defaults to patch automatically, that is not what I am seeing.

```
uses: paulhatch/semantic-version@v5.4.0
with:
    # The prefix to use to identify tags
    # tag_prefix: "v"
    # A string which, if present in a git commit, indicates that a change represents a 
    # major (breaking) change, supports regular expressions wrapped with '/'
    major_pattern: "(MAJOR)"
    # A string which indicates the flags used by the `major_pattern` regular expression. Supported flags: idgs
    major_regexp_flags: ""
    # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
    minor_pattern: "(MINOR)"
    # A string which indicates the flags used by the `minor_pattern` regular expression. Supported flags: idgs
    minor_regexp_flags: ""
    # A string to determine the format of the version output
    version_format: "${major}.${minor}.${patch}-beta"
    # Optional path to check for changes. If any changes are detected in the path the
    # Named version, will be used as suffix for name version tag
    namespace: "beta"
    # If this is set to true, *every* commit will be treated as a new version.
    bump_each_commit: false
    # If bump_each_commit is also set to true, setting this value will cause the version to increment only if the pattern specified is matched.
    bump_each_commit_patch_pattern: ""
    # If true, the body of commits will also be searched for major/minor patterns to determine the version type.
    search_commit_body: true
    # The output method used to generate list of users, 'csv' or 'json'.
    user_format_type: "json"
```
