### DISCUSSION TITLE
Is it possible to automatically bump minor version if executed from `main` and `patch` if executed from other branches?

### DISCUSSION THREAD

**Discussion by eptw4by** [PaulHatch/semantic-version#167] [Q&A] [answered]
Is it possible to automatically bump minor version if executed from `main` and `patch` if executed from other branches? 
I need to distinguish when my service was built from main and when - from branch.

**Comment by PaulHatch** [comment, marked as answer]
In general this action looks at commits and not branch names, the only exception being when the "version from branch" option is enabled. You can create multiple GitHub Actions workflows for different branches:

```
on:
  push:
    branches:
      - master
```

You could also just check the branch name in the action itself with some custom code and pass the configuration variables into the action.

At the moment there is not a clean way to override the type of commit. You could set up the action that runs on the master branch with a `minor_pattern` that always matches, but you'd need to set a tag in that case if you want that to reflect on both branches because if you used `bump_each_commit` each branch will reflect it's own configuration and won't know that the config in the other branch resulting in a minor bump. If you do set a tag in the action make sure to set the parallelism on the workflow to 1 to prevent race conditions since the tag won't be reflected in multiple runs that start at the same time.

For version 6 I am planning to allow you to override the values that are calculated from the Git repo using parameters, so you would be able to do something like set `branch_type: "minor"`, but I'm a bit behind getting started on that at the moment.

**Reply by eptw4by** [reply]
Thank you. 
So, I would just specify something like this for branches other then main: 

```
      uses: paulhatch/semantic-version@v5.4.0
      with:
        # The prefix to use to identify tags
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        major_regexp_flags: ""
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}"
        bump_each_commit: false
        bump_each_commit_patch_pattern: ""
        search_commit_body: true
        user_format_type: "csv"
        enable_prerelease_mode: false
        version_from_branch: true
```

and for main it could be something like this:
```
      uses: paulhatch/semantic-version@v5.4.0
      with:
        # The prefix to use to identify tags
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        major_regexp_flags: ""
        minor_pattern: "/.*/"
        version_format: "${major}.${minor}.${patch}"
        bump_each_commit: false
        bump_each_commit_patch_pattern: "(PATCH)"
        search_commit_body: true
        user_format_type: "csv"
        enable_prerelease_mode: false
        version_from_branch: true
```
