### DISCUSSION TITLE
Version not incrementing as expected

### DISCUSSION THREAD

**Discussion by h-joshi** [PaulHatch/semantic-version#174] [Q&A]
Pasted below is a portion of the Git workflow I currently have

- On the very first run tag `v0.0.1` was created
- A message was displayed `Warning: None of the 1 tags(s) found were valid version tags for the present configuration. If this is unexpected, check to ensure that the configuration is correct and matches the tag format you are using.`
- Made some code changes and ran the workflow again See **log entry [A]** below
- I expected it to increment the version to v0.0.2, but that did not occur.

Would appreciate any advice as to what mis-configuration is prevent the version/tags from being properly incremented.

```
      - name: Create version
        id: create_version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          bump_each_commit: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: /tmp/body.txt
          name: ${{ steps.create_version.outputs.version_tag }}
          tag_name: ${{ steps.create_version.outputs.version }}
          files: |
            grc_fixes.tsv
          generate_release_notes: true
          token: ${{ github.token }}
```

**Log entry [A]**
![image](https://github.com/user-attachments/assets/b44ed0be-adbc-4e7e-af11-c4acfd92f015)
