### DISCUSSION TITLE
How can I get the generated version in a different step of the job?

### DISCUSSION THREAD

**Discussion by tfg2021-escinf-una** [PaulHatch/semantic-version#48] [Q&A] [answered]
Hey @PaulHatch, I'm using your action to generate the versions, however, I am not to sure in which variable does your action save the generated version. 

If I use ${version} it is coming as blank. Could you please give me a hand? 

The file I'm using contains the following commands: 
![image](https://user-images.githubusercontent.com/94311018/162856919-da2f033d-d88b-441a-bad2-2532a7731ace.png)

**Comment by tfg2021-escinf-una** [comment, marked as answer]
Nevermind, I already figured it out. 
Thanks!

**Reply by PaulHatch** [reply]
Great, for future reference, this was the use of single `${}` instead of double `${{}}`, right?

**Comment by PaulHatch** [comment]
Looks like you are trying to use the ${{ version }} directly in the action. You’d need to include the full path of the output you are trying to reference like ${{ steps.version.outputs.version }}.

**Comment by DechertNicholas** [comment]
For anyone still confused by this, I got it figured out. Add an `id` named `version` or whatever you want to your version step:

```
- name: Setup Versioning
      uses: paulhatch/semantic-version@v5.0.3
      id: version
      with:
        # The prefix to use to identify tags
        tag_prefix: "v"
        # A string which, if present in a git commit, indicates that a change represents a
        # major (breaking) change, supports regular expressions wrapped with '/'
        major_pattern: "(MAJOR)"
        # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
        minor_pattern: "(MINOR)"
        # A string to determine the format of the version output
        version_format: "${major}.${minor}.${patch}.${increment}"
        # If this is set to true, *every* commit will be treated as a new version.
        bump_each_commit: false
        # If true, the body of commits will also be searched for major/minor patterns to determine the version type.
        search_commit_body: true
```

Then access it as an environment variable, after specifically setting it as an environment variable in the `env:` section

```
- name: Set Package Version
      run: |
        ...
        Write-Output "Version: $env:FullVersion"
        ...
      env:
        FullVersion: ${{ steps.version.outputs.version }}
```

I'm sure there's also an easier way to do this, but for someone new to GithubActions, this wasn't immediately obvious to me.
