### ISSUE TITLE
Fails to read/parse existing version

### ISSUE THREAD

**Issue by chlirre** [PaulHatch/semantic-version#1]
I keep getting `Version is 0.0.1+0` when using this action.

I ran https://github.com/PaulHatch/semantic-version/blob/master/index.js#L59-L66 locally as

```
git for-each-ref  --format='%(refname:short)' --sort=-committerdate --no-contains <commit> refs/tags/v*
```

and got 

```
v0.1.5
v0.1.4
v0.1.3
v0.1.2
v0.1.1
v0.1.0
```

Output when running the action:
```
Run PaulHatch/semantic-version@v1.0.1
  with:
    branch: master
    tag_prefix: v
    format: v${major}.${minor}.${patch}
    major_pattern: (MAJOR)
    minor_pattern: (MINOR)
  env:
    GITHUB_TOKEN: ***
Version is 0.0.1+0
```
