### ISSUE TITLE
Change base from where increment starts

### ISSUE THREAD

**Issue by Vadorequest** [PaulHatch/semantic-version#10]
I understand this action will start counting from `1.0.0`. This is a great default, but doesn't cover the cases where we'd add this action after we created a few (or hundreds) tags.

Could it be possible to not start counting from `1.0.0`, like by providing another input `baseTag: 1.2.3` for instance?

This might widen adoption, otherwise we'd have to make many (minor) or (major) fake commits to match our current tag, and that's a bit messy.

**Comment by PaulHatch** [comment]
It actually starts at 0.0.0 by default, but if you have a tag that matches it will use that instead. If it isn't picking up your tag, make sure that the prefix matches what you're using (e.g. with a 'v' or just the number).

**Comment by Vadorequest** [comment]
It's picking the major tag but not minor ones. (`v1.0.1` found as next version, but I have `v1.1.2` released already at https://github.com/UnlyEd/github-action-await-vercel/releases)

See https://github.com/UnlyEd/github-action-await-vercel/pull/7
Workflow runs for the action: https://github.com/UnlyEd/github-action-await-vercel/actions?query=workflow%3A%22Auto+version+increment%22

Logs example: https://github.com/UnlyEd/github-action-await-vercel/runs/1579463576?check_suite_focus=true

**Comment by PaulHatch** [comment]
So it seems that in this repo there is this commit:

` bc4a1fc (tag: v1.1.2, tag: v1, tag: latest) Improve doc again (2)`

This has the tag `v1.1.2` which is what you're expected, but also the tag `v1`, which is going to be interpreted as v1.0.0. It seems that this tag is "winning", meaning the version being picked up as 1.0.0.

Let me give some thought as how to handle this. The semantic version spec does not actually cover git tags, only the semantic version portion, and just "1" by itself is not a valid semantic version but a commonly used tag format. I am guessing by your usage that you'd be updating this tag continuously to point to the latest major version1?

**Comment by Vadorequest** [comment]
Yes, exactly, it's to support the common `@v1`, `@v2`, etc. which are supposed to be auto-patched tags with minor/patch updates to ease maintenance.

More details at https://github.com/UnlyEd/github-action-await-vercel/blob/0ab46b5a9a14c120dc434d810888dbadefc772ab/.github/workflows/auto-tag-on-release.yml which is the action that does this automatically.

I suppose those "major" versions (that's how I call them, no better term known) should indeed be ignored.

**Comment by Vadorequest** [comment]
So, I succeeded in retrieving the version (using your action) and publishing a new release (using another action). For the moment, the release is stuck at 1.0.1 indeed.
https://github.com/UnlyEd/github-action-await-vercel/releases/tag/v1.0.1

I'll wait for a fix before merging my PR, but besides that small "bug" everything works fine!

```yml
# Summary:
# Automatically increase the version using semantic versioning
#
# See https://github.com/PaulHatch/semantic-version https://github.com/PaulHatch/semantic-version/tree/v3.1.2
# See https://github.com/marvinpinto/action-automatic-releases https://github.com/marvinpinto/action-automatic-releases/tree/v1.1.0

name: 'Auto version increment'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - '*' # XXX for testing

jobs:
  run-semantic-versioning:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See https://github.com/PaulHatch/semantic-version#important-note-regarding-the-checkout-action
      - uses: paulhatch/semantic-version@v3.1.2
        id: next_semantic_version # Output: https://github.com/PaulHatch/semantic-version/blob/master/index.js#L63-L69
        with: # See https://github.com/PaulHatch/semantic-version#usage
          branch: main # Force "main" instead of "master" by default
          tag_prefix: "v" # The prefix to use to identify tags
          major_pattern: "(MAJOR)" # A string which, if present in a git commit, indicates that a change represents a major (breaking) change
          minor_pattern: "(MINOR)" # Same as above except indicating a minor change
          format: "${major}.${minor}.${patch}-prerelease.${increment}" # A string to determine the format of the version output
      - run: |
          echo ${{join(steps.next_semantic_version.outputs.*, ' - ')}}
          echo "Next version: ${{steps.next_semantic_version.outputs.version}}"
          echo "Next version tag: ${{steps.next_semantic_version.outputs.version_tag}}"
      - uses: marvinpinto/action-automatic-releases@v1.1.0
        with: # See https://github.com/marvinpinto/action-automatic-releases/tree/v1.1.0#supported-parameters
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{steps.next_semantic_version.outputs.version_tag}}
          prerelease: true
          title: "Automatic release ${{steps.next_semantic_version.outputs.version_tag}}"
          files: |
            CHANGELOG.md

```
