### ISSUE TITLE
Incorrect version detected

### ISSUE THREAD

**Issue by hoopty** [PaulHatch/semantic-version#106]
Hello -

It seems the latest version to use is not properly detected, it may be related that we had some releases with the **v** prefix and others without.  Unfortunately this is a private repo so I can't give you access, but I'd be happy to run your node app against my local repo with debug flags or the like to help diagnose.  I'm expecting my version to be `v3.0.7-prerelease???` but it is coming up with `v3.0.1-prerelease???`.  Hope this gets you the relevant info...

Here's the pipeline snippet:
```
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0      

        # https://github.com/PaulHatch/semantic-version
      - name: Version
        id: version
        uses: paulhatch/semantic-version@v5.0.3
        with:
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          search_commit_body: true
```

Here's the pipeline output:
<img width="692" alt="Screen Shot 2023-05-02 at 16 58 48 PM" src="https://user-images.githubusercontent.com/552149/235795142-54ec6e1b-5ebd-4bca-9f2e-3e3a39d67319.png">

Here's the GH releases (from GH cli):
```TITLE    TYPE    TAG NAME  PUBLISHED
v3.0.7   Latest  v3.0.7    about 22 days ago
3.0.6            v3.0.6    about 1 month ago
3.0.5            v3.0.5    about 2 months ago
3.0.4            v3.0.4    about 2 months ago
v3.0.3           v3.0.3    about 3 months ago
v3.0.2           v3.0.2    about 3 months ago
v3.0.1           v3.0.1    about 5 months ago
3.0.0            v3.0.0    about 7 months ago
2.0.31           2.0.31    about 7 months ago
2.0.30           v2.0.30   about 8 months ago
```
Here's the start and end of the tags (from `git tag`):
```
1.0.51
2.0.10
2.0.13
2.0.14
2.0.2
2.0.2-beta-2
2.0.3
2.0.31
2.0.4-beta
2.0.4-beta-2
v1
v1.0.1
... (remove interim vX.Y.Z* tags)
v2.05-beta
v2.06-beta
v2.07
v3.0.0
v3.0.1
v3.0.2
v3.0.3
v3.0.4
v3.0.5
v3.0.6
v3.0.7
```
