### ISSUE TITLE
No tags are present for this repository (fetch-depth: 0)

### ISSUE THREAD

**Issue by osilva-creditas** [PaulHatch/semantic-version#109]
For some reason that idk, it is not detecting the repo tags.

Its working only when i merge to master, but not merging to develop and staging

This is my setup. Please help. 

```
Run PaulHatch/semantic-version@v5.0.3
  with:
    tag_prefix: release-v
    version_format: ${major}.${minor}.${patch}-${increment}
    branch: HEAD
    use_branches: false
    major_pattern: (MAJOR)
    minor_pattern: (MINOR)
    bump_each_commit: false
    search_commit_body: false
    user_format_type: csv
Warning: No tags are present for this repository. If this is unexpected, check to ensure that tags have been pulled from the remote.
Version is 1.0.0-40
``` 

The Setup for checkout:

```
    - name: Checkout this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
``` 

also i try only this

```
    - name: Checkout this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
``` 

And this is the fetch output:

```
   * [new branch]      master           -> origin/master
   * [new branch]      release/1.1.0    -> origin/release/1.1.0
   * [new branch]      release/1_0_0    -> origin/release/1_0_0
   * [new branch]      release/1_1_0    -> origin/release/1_1_0
   * [new branch]      staging          -> origin/staging
   * [new branch]      task/BGC-1168    -> origin/task/BGC-1168
   * [new tag]         release-v1.0.0   -> release-v1.0.0
   * [new tag]         release-v1.0.1   -> release-v1.0.1
   * [new tag]         release-v1.0.2   -> release-v1.0.2
   * [new tag]         release-v1.0.3   -> release-v1.0.3
``` 

This output is when i merge stg to master
![image](https://github.com/PaulHatch/semantic-version/assets/96446627/9419896f-2a85-46d2-8228-19f0b3f11dff)

Sorry for my bad english

**Comment by osilva-creditas** [comment]
I dont really know what happens and how it works, but when I use this setup, it works.

This is when i create a PR feature->develop

```
- name: Generate version
        id: generate-version
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          tag_prefix: "release-v"
          version_format: "${major}.${minor}.${patch}-${increment}"
          branch: "origin/master"
```

**Comment by osilva-creditas** [comment]
Ok I think I fixed the issue.

In the develop branch i run this: 

```shell
git reset --hard master
``` 

them i recreated the feature branch.

Create the pr again and now it works.

**Comment by PaulHatch** [comment]
Hey @osilva-creditas, glad you found a workaround, but from looking at your setup I'm not clear what the issue is. Generally you should not need to set the branch ever unless perhaps you're doing something very unusual (even then I'm not sure what that case would be, this setting is left over from a very early version of this action).

If you can provide a [test case](https://github.com/PaulHatch/semantic-version/blob/master/contributing.md#providing-a-test-case) that illustrates your setup and the problem you are experiencing that would be helpful.

**Comment by osilva-creditas** [comment]
Hi @PaulHatch, thank you very much for answering

Let me explain first what i did

First we have this workflow:

feature->develop->staging->master

Only when we merge into master the job create the tag and the realease.

So, what I want is to deploy a new version in all environments with the same number (ex: 1.0.5), taking the last tag that was made from master as the latest version (1.0.4).

The problem that I have is deploying "develop", it is not taking the last tag, it shows me the error "No tags are present for this repository", If the last tag is 1.0.4, I expect the version to be 1.0.5, but it is 1.0.0-40

I think the issue is that the develop branch is a mess and has much more commits than master, and when it compares the commits with the last tag created, it is not able to find the differences, so when I restart develop from master, everything works.

When I can do the test case I will share it, for now I leave the complete setup file that I use.

```
name: Build and Deploy to Cloudhub

on:
  pull_request:
    branches: [ develop, staging, master ]
    types: [opened, reopened, synchronize, review_requested, closed]

jobs:
  setting:
    if: github.event.pull_request.merged == true || github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6
    - name: Checkout this repo
      uses: actions/checkout@v3.5.2
      with:
        fetch-depth: 0
    - name: Generate version
      id: generate-version
      uses: PaulHatch/semantic-version@v5.0.3
      with:
        tag_prefix: "release-v"
        version_format: "${major}.${minor}.${patch}-${increment}"
    - name: Setting Application Name
      id: setting-name
      env:
        app_name: "-${{ steps.branch-name.outputs.base_ref_branch }}"
      run: |
        echo "app_name=$app_name" >> $GITHUB_OUTPUT
    outputs:
      env_name: ${{ steps.branch-name.outputs.base_ref_branch }}
      app_name: ${{ steps.setting-name.outputs.app_name }}
      app_version: ${{ steps.generate-version.outputs.version }}
      app_version_tag: ${{ steps.generate-version.outputs.version_tag }}

  test:
    needs: setting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3.5.2
      with:
        fetch-depth: 0
    - name: Cache dependencies restore
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Test with Maven
      env:
        mule_repo_username: ${{ secrets.mule_repo_username }}
        mule_repo_password: ${{ secrets.mule_repo_password }}
        username: ${{ secrets.anypoint_platform_username }}
        password: ${{ secrets.anypoint_platform_password }}
      run: |
          mvn test --settings settings.xml \
          -Danypoint.username="$username" \
          -Danypoint.password="$password" \
          -DapplicationName="${{ needs.setting.outputs.app_name }}"
    - name: Upload MUnit reports
      uses: actions/upload-artifact@v3
      with:
        name: "munit-test-reports-${{ needs.setting.outputs.app_name }}-${{ needs.setting.outputs.app_version }}"
        path: target/site/munit/coverage/

  build:
    if: github.event.pull_request.merged == true
    needs: [setting, test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3.5.2
      with:
        fetch-depth: 0
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Updating project version
      run: mvn versions:set -DnewVersion="${{ needs.setting.outputs.app_version }}"
    - name: Build with Maven
      id: build-baven
      env:
        mule_repo_username: ${{ secrets.mule_repo_username }}
        mule_repo_password: ${{ secrets.mule_repo_password }}
        username: ${{ secrets.anypoint_platform_username }}
        password: ${{ secrets.anypoint_platform_password }}
      run: |
        mvn -B package --file pom.xml --settings settings.xml -DskipMunitTests \
        -Danypoint.username="$username" \
        -Danypoint.password="$password" \
        -DapplicationName="${{ needs.setting.outputs.app_name }}"
    - name: Stamp artifact file name with commit hash
      run: |
        artifactName1=$(ls -rth target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(ls -rth target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
        mv $artifactName1 $artifactName2
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: "${{ needs.setting.outputs.app_name }}-${{ needs.setting.outputs.app_version }}"
          path: target/*.jar
    - name: Create tag and push
      if: needs.setting.outputs.env_name == 'master'
      run: git tag ${{ needs.setting.outputs.app_version_tag }} && git push --tags

  deploy:
    needs: [setting, build]
    runs-on: ubuntu-latest
    environment:
      name: "mulesoft-${{ needs.setting.outputs.env_name }}"
    steps:
    - name: Deploy Details
      run: |
        echo "Environment: ${{ needs.setting.outputs.env_name }}"
        echo "Application Name: ${{ needs.setting.outputs.app_name }}"
        echo "Version: ${{ needs.setting.outputs.app_version }}"
    - name: Checkout this repo
      uses: actions/checkout@v3.5.2
      with:
        fetch-depth: 0
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: actions/download-artifact@v3
      with:
        name: "${{ needs.setting.outputs.app_name }}-${{ needs.setting.outputs.app_version }}"
    - name: Updating project version
      run: mvn versions:set -DnewVersion="${{ needs.setting.outputs.app_version }}"
    - name: Deploy to Cloudhub
      env:
        mule_repo_username: ${{ secrets.mule_repo_username }}
        mule_repo_password: ${{ secrets.mule_repo_password }}
        username: ${{ secrets.anypoint_platform_username }}
        password: ${{ secrets.anypoint_platform_password }}
        business_group_id: ${{ secrets.anypoint_business_group_id }}
        anypoint_platform_client_id: ${{ secrets.anypoint_platform_client_id }}
        anypoint_platform_client_secret: ${{ secrets.anypoint_platform_client_secret }}
      run: |
        artifactName=$(ls -rth *.jar | head -1) \
        mvn --settings settings.xml deploy -DskipMunitTests -DmuleDeploy \
          -Dmule.artifact=$artifactName \
          -DanypointUsername="$username" \
          -DanypointPassword="$password" \
          -DbusinessGroupId="$business_group_id" \
          -DanypointPlatformClientId="$anypoint_platform_client_id" \
          -DanypointPlatformClientSecret="$anypoint_platform_client_secret" \
          -DanypointPlatformBaseUri="${{ vars.anypoint_platform_base_uri }}" \
          -DanypointPlatformAnalyticsBaseUri="${{ vars.anypoint_platform_analytics_base_uri }}" \
          -DanypointPlatformConfigAnalyticsAgentEnabled="${{ vars.anypoint_platform_config_analytics_agent_enabled }}" \
          -Dworkers="${{ vars.workers }}" \
          -DworkerType="${{ vars.workerType }}" \
          -Denvironment="${{ vars.mule_env }}" \
          -DapplicationName="${{ needs.setting.outputs.app_name }}" \
          -DlistenerPort="${{ vars.listener_port }}" \
    - name: Generate release
      if: needs.setting.outputs.env_name == 'master'
      uses: Roang-zero1/github-create-release-action@v3
      with:
        created_tag: "${{ needs.setting.outputs.app_version_tag }}"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

```
