### ISSUE TITLE
Namespace not working

### ISSUE THREAD

**Issue by jschwellnus92** [PaulHatch/semantic-version#111]
Tried v5.0.2 and v5.0.3 of the action.

In this screenshot you can see a namespace is provided but the output version does not include a namespace:
![image](https://github.com/PaulHatch/semantic-version/assets/39755231/6ffd7887-03a5-43b5-a9a8-715fa07a4da9)

This is the workflow:
````
name: Tagging workflow

on:
  push: 
    branches:
    - main

jobs:
  tagging-billing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate Version
        id: versioning
        uses: paulhatch/semantic-version@v5.0.2
        with:
          change_path: "billing"
          namespace: "billing"
          major_pattern: "(MAJOR-billing)"
          minor_pattern: "(MINOR-billing)"
      - name: Tag Release
        if: ${{ steps.versioning.outputs.changed == 'true' }}
        run: |
          git tag v${{ steps.versioning.outputs.version }}
          echo "Created tag v${{ steps.versioning.outputs.version }}" 
          git push --tags
          echo "Pushed tag v${{ steps.versioning.outputs.version }} to origin" 
        shell: bash
````

Directory structure:
![image](https://github.com/PaulHatch/semantic-version/assets/39755231/fd624a3b-ef4f-429a-8d38-032c16dda457)

And the resulting tag that is generated:
![image](https://github.com/PaulHatch/semantic-version/assets/39755231/805b0194-77f8-4b80-819d-524406ec6bad)
