### ISSUE TITLE
No tags are present for this repository

### ISSUE THREAD

**Issue by nikwal-encare** [PaulHatch/semantic-version#117]
Get a warning about not tags are present in this repository and the version is not picked up:

The tag listing show:
```
> git describe --tags --abbrev=0
v0.4.0
> git tag
v0.2.0
v0.3.0
v0.4.0
> git for-each-ref --sort="-v:*refname" --format="%(refname:short)" --merged=HEAD "refs/tags/v*[0-9].*[0-9].*[0-9]"
v0.4.0
v0.3.0
v0.2.0
```

The version output is:
0.1.0-14
Expected version:
0.4.0-14

```
jobs:
  build:
    name: 🏗 Build
    runs-on: ubuntu-latest
    outputs:
      sversion: ${{ steps.semversion.outputs.version }}

    steps:
    - name: ⬇ Checkout 
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Tags
      run: git tag
       
    - name: 🔢 Semantic version 
      id: semversion
      uses: paulhatch/semantic-version@v5.2.0
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        major_regexp_flags: ""
        minor_pattern: "(MINOR)"
        minor_regexp_flags: ""
        version_format: "${major}.${minor}.${patch}-${increment}"
        change_path: "."
        namespace: Example
        bump_each_commit: false
        bump_each_commit_patch_pattern: ""
        search_commit_body: false
        user_format_type: "csv"
        enable_prerelease_mode: false

```
