### ISSUE TITLE
Usage of `bump_each_commit_patch_pattern`

### ISSUE THREAD

**Issue by hkolvenbach** [PaulHatch/semantic-version#125]
First of all, thanks for this great github action! It makes versioning our release binaries really easy.

I tried to use the new `bump_each_commit_patch_pattern` configuration, but I am unsure if I understand it correctly. I am trying to set it up so that minor and major versions are bumped on `MINOR` and `MAJOR` keywords, and the `PATCH` version is bumped only if any message since the last tag contains the `PATCH` keyword.

Are these assumptions correct?
- if the pattern (i.e. `PATCH` is present in a commit, the version will be bumped
- if the pattern is not present, the version will not be bumped

I am using the following configuration, but the version now jumps (i.e. `v3.2.5` is the last tag, and `semantic-version` reports `v3.2.9` as the next version after 4 commits, even though none of them contain `PATCH`). I would expect the reported next version to be `v3.2.6`.

My config:
```
- name: Increase the version
      id: versioning
      uses: paulhatch/semantic-version@v5.1.0
      with:
        tag_prefix: "v"
        major_pattern: "MAJOR"
        minor_pattern: "MINOR"
        bump_each_commit: true
        bump_each_commit_patch_pattern: "PATCH"
```
