### ISSUE TITLE
zero-pad increment

### ISSUE THREAD

**Issue by astldev** [PaulHatch/semantic-version#128]
How can I zero-pad the increment?

**Comment by PaulHatch** [comment]
It is not possible at the moment to do this type of formatting in the action. At the moment you can specify a format by setting the `version_format` parameter, which defaults to `"${major}.${minor}.${patch}-prerelease${increment}"`. Internally this is implemented with a simple string replace.

I've had mixed feelings about this, the format impacts the output only but sometimes people have mistakenly believed it was used to set the input format.

Anyway, all the values are available as outputs, so you can just format this in a subsequent step like so something like this:

```yaml
...
- name: Format Version
  id: format-version
  run: echo "::set-output name=version::$MAJOR.$MINOR.$PATCH-$(printf '%03d' $INCREMENT)"
  env:
    MAJOR: {{ steps.version.outputs.major }}
    MINOR: {{ steps.version.outputs.minor }}
    PATCH: {{ steps.version.outputs.patch }}
    INCREMENT: {{ steps.version.outputs.increment }}
```
