### ISSUE TITLE
`version_from_branch` usage

### ISSUE THREAD

**Issue by kirillmorozov** [PaulHatch/semantic-version#136]
Hi,

First of all I'd like to thank you for a very helpful action that I use everywhere I can.

Version 5.3.0 introduced branch-based versioning mode which I use in a repo that uses release branches.

We create a branch from our default branch named `release/MAJOR.MINOR` where MAJOR and MINOR are corresponding parts of version that we expect to release from this branch and then start a release workflow that resolves version using your action and then creates a GitHub release.

Today I started this release workflow from `release/11.2` branch and was very surprised to discover that the resolved version was `12.0.0` while I've expected it to be `11.2.0`.

This is the output of Checkout action that shows the branch name:

```console
/usr/bin/git checkout --progress --force -B release/11.2 refs/remotes/origin/release/11.2
```

And here are the inputs I use for your action:

```yaml
uses: paulhatch/semantic-version@v5.3.0
with:
  debug: true
  tag_prefix: ""
  version_from_branch: true
  major_pattern: '/^\w*(?:\(\w*\))?!:/'
  minor_pattern: '/^feat(?:\(\w*\))?!?:/'
  version_format: ${major}.${minor}.${patch}
  bump_each_commit: false
  search_commit_body: false
  namespace: ""
```

And here's a warning I got for this run but I'm not sure what it means:

```console
Warning: None of the 1 tags(s) found were valid version tags for the present configuration. If this is unexpected, check to ensure that the configuration is correct and matches the tag format you are using.
```

Could you please explain how to correctly configure this action to use branch-based versioning?

I'm also interested in a way to use this action in a flow that has a default branch and release branches from it. So far I came up with a workaround to create `MAJOR.MINOR.0` tags on a commit I create `release/MAJOR.MINOR` branch from so that this action can resolve future versions based on this tag but I'm not sure this is a best option.
