### ISSUE TITLE
Feature request: support glob/asterisk in change_path 

### ISSUE THREAD

**Issue by Shaked** [PaulHatch/semantic-version#145]
The idea is to have an option to generate a version based on a more dynamic path. For example:

```
      - uses: paulhatch/semantic-version@v5.4.0
        name: Generate version
        id: version
        with:
          tag_prefix: ""
          bump_each_commit: true
          version_format: "${major}.${minor}.${patch}"
          change_path: "path/**/platform"
``` 

In my case, I have dynamically generated directories under `path` and I want to follow all changes under their `./platform` directory and tag it. 

Another idea would be to support a file pattern, like all files containing a specific string or extension e.g. `platform_*.yaml` or `*.yaml` 

WDYT?
