### ISSUE TITLE
v Tags being ignored

### ISSUE THREAD

**Issue by eldir** [PaulHatch/semantic-version#165]
v prefixed tags seem to be ignored:
Standard main/development branch setup, I've added version tags here in two places to test this and the version output for the last commit here is '0.7.46-alpha.135'
![image](https://github.com/user-attachments/assets/96c44148-daf6-4e07-ab67-1fb2a3d1696f)

Workflow settings:
```      
- name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          enable_prerelease_mode: true
          tag_prefix: "v"
          search_commit_body: true
          bump_each_commit: true
          major_pattern: "[MAJOR]"
          minor_pattern: "[MINOR]"
          version_format: "v${major}.${minor}.${patch}"
```

Workflow output for the above step:
![image](https://github.com/user-attachments/assets/aec4d709-52fd-4ff0-a8b8-ecd32ce1dc5e)
