### ISSUE TITLE
Version tag warning despite working correctly

### ISSUE THREAD

**Issue by andrin55** [PaulHatch/semantic-version#169]
Hi 

Thank you for providing this action, it works great!
I have however a warning which I cannot seem to get rid of:
`Warning: None of the X tags(s) found were valid version tags for the present configuration. If this is unexpected, check to ensure that the configuration is correct and matches the tag format you are using.`

I use the action like this:
```
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          # include the history and tags to generate semantic version
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Generate semantic version based on git history
        id: version
        uses: paulhatch/semantic-version@a8f8f59fd7f0625188492e945240f12d7ad2dca3 # pin @v5.4.0
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          # Define patterns to use for bumping the major and minor version.
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          # If this is set to true, every commit will be treated as a new version.
          # We need this in order to have unique image tags for each commit.
          bump_each_commit: true
```

Now if I have a repo without any explicit tags the warning shows up with "None of the 1 tags(s) found".

If i have a repo with a single version tag it shows up with "None of the 2 tags(s) found":
```
$ git tag
v1.2.0
```

The version will get set correctly in both cases (once with commit messages and once with the tag), but it would be nice if there was no warning.

Is there anything I can change or is this a bug in the action?
