### ISSUE TITLE
No tags are present for this repository.

### ISSUE THREAD

**Issue by krupitskas** [PaulHatch/semantic-version#20]
Hey! Im still trying to setup your GitHub Actions and it still doesn't work for me

```
Run paulhatch/semantic-version@v3.3
  with:
    branch: versioning
    tag_prefix: v
    major_pattern: (major!)
    minor_pattern: (minor!)
    format: ${major}.${minor}.${patch}
    short_tags: false
    bump_each_commit: false
  env:
    BUILD_TYPE: Release

The command 'git describe --tags --abbrev=0 --match=v[0-9]+\.[0-9]+\.[0-9]+ origin/versioning~1' failed: Error: The process '/usr/bin/git' failed with exit code 128

stderr: fatal: No names found, cannot describe anything.

Warning: No tags are present for this repository. If this is unexpected, check to ensure that tags have been pulled from the remote.

Version is 0.0.1+69

To create a release for this version, go to https://github.com/dungeonfog/deios/releases/new?tag=v0.0.1&target=versioning
```

However I also check which tags are available and have next output:
<img width="924" alt="Screenshot 2021-02-05 at 21 51 07" src="https://user-images.githubusercontent.com/5683877/107076274-427f7180-67fc-11eb-993c-c09cb18b372e.png">

My idea is increment patch tag each time I push new commit in this branch (after this actions will be only triggered on push into main)

This is my script with semantic tag and create release:

```
 - uses: paulhatch/semantic-version@v3.3
          id: versioning
          with:
            branch: "versioning"
            tag_prefix: "v"
            major_pattern: "(major!)"
            minor_pattern: "(minor!)"
            format: "${major}.${minor}.${patch}"
            short_tags: false
            bump_each_commit: false

        - uses: ncipollo/release-action@v1
          with:
            name: Release - ${{ steps.versioning.outputs.version }}
            artifacts: "macos-deios.zip" # , windows-deios.zip, linux-deios.zip
            token: ${{ secrets.GITHUB_TOKEN }}
            draft: true
            commit: ${{ env.GITHUB_SHA }}
            tag: ${{ steps.versioning.outputs.version_tag }}
            allowUpdates: true
            body: |
              ${{ steps.Changelog.outputs.changelog }}
              
```

p.s.
Also in your docs it looks like copy-paste issue, but Im not sure
```
- uses: paulhatch/semantic-version@v3.3
  with:
    # The prefix to use to identify tags <- this
    branch: "master"
    # The prefix to use to identify tags <- and this
    tag_prefix: "v"
    ```

**Comment by PaulHatch** [comment]
Hello Nikita, thanks for reporting this.

Your action is running on the `versioning` branch? On reviewing this, I believe that using the current HEAD would be a superior default for this action vs specifying the branch and might resolve your issue.

[This pull request](https://github.com/PaulHatch/semantic-version/pull/21) adds support for HEAD and uses this branch by default, could you see if using this resolves your problem?

```
- uses: paulhatch/semantic-version@feature/HeadRef
  id: versioning
  with:
    major_pattern: "(major!)"
    minor_pattern: "(minor!)"
```
(Note that this branch will be deleted once it is merged)

You are correct regarding the doc, with this change I will drop the branch name from the example as most users will not need to assign this value going forward.

**Comment by PaulHatch** [comment]
This PR still has issues, I need to look at this further

**Comment by krupitskas** [comment]
Hey @PaulHatch, thanks for a quick response. I'm using versioning branch for a testing purpose, because we can't push into main directly, so I need to be sure that my GitHub workflow works. 

Okay, then I'll wait for some news from you :)

**Comment by PaulHatch** [comment]
Hey @krupitskas, [v4](https://github.com/PaulHatch/semantic-version/releases/tag/v4) is now available. Going forward I think simply taking the repo's HEAD and dispensing with the branch should cover pretty much all use cases. Would appreciate it if you could let me know if this resolves the issue you saw.

**Comment by iceicys** [comment]
@PaulHatch I'm trying v4 with the below YML and I'm getting the following error:
**stderr: fatal: No names found, cannot describe anything.
Warning: No tags are present for this repository. If this is unexpected, check to ensure that tags have been pulled from the remote.**

```yml
on:
  push:
    branches: 'release/230.0.0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: paulhatch/semantic-version@v4
      with:
        branch: "HEAD"
        tag_prefix: ""
        major_pattern: "230"
        minor_pattern: "0"
        format: "${major}.${minor}.${patch}-RC${increment}"
        short_tags: false
        bump_each_commit: true
```
Branch Tag and Creation YML
```yml
name: Cut Release
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Release #major.#minor.#patch (230.0.0)'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create release branch
      run: git checkout -b release/${{ github.event.inputs.versionName }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Push new branch
      run: git push origin release/${{ github.event.inputs.versionName }}
    - name: Checkout branch "release/${{ github.event.inputs.versionName }}"
      uses: actions/checkout@v2
      with:
          ref: 'release/${{ github.event.inputs.versionName }}'
    - name: Create tag on new branch
      uses: actions/github-script@v3
      with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ github.event.inputs.versionName }}",
              sha: context.sha
            })
```

![image](https://user-images.githubusercontent.com/73564034/107385555-fdd82c80-6ac0-11eb-8b9c-6446dbc74d3d.png)


I know a tag exists on the branch, does the tag have to exist only on HEAD of origin?
