### ISSUE TITLE
Support for non-master named branches

### ISSUE THREAD

**Issue by iceicys** [PaulHatch/semantic-version#22]
Our repos have moved from using master to `develop`, https://github.com/github/renaming. 

I am hoping to be able to use this action to update tags independently on multiple release branches, but when I specific a branch name I'm encountering the following error. 

> The command 'git tag --points-at origin/master v*[0-9.] ' failed: Error: The process '/usr/bin/git' failed with exit code 129
stderr: error: malformed object name 'origin/master'
> The command 'git describe --tags --abbrev=0 --match=v*[0-9.] origin/master~1' failed: Error: The process '/usr/bin/git' failed with exit code 128
> stderr: fatal: No names found, cannot describe anything.
> Warning: No tags are present for this repository. If this is unexpected, check to ensure that tags have been pulled from the remote.

How can I use this solution for release branching and in repos that do not contain a branch named `master`?

![image](https://user-images.githubusercontent.com/73564034/107221617-deb69d80-69e1-11eb-9e29-2118bb17cf57.png)

![image](https://user-images.githubusercontent.com/73564034/107221418-9dbe8900-69e1-11eb-99f5-76b4b596a1cf.png)

```yaml
name: 230.0.0 Increment Tags

on:
  push:
    branches: 'release/230.0.0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: paulhatch/semantic-version@feature/HeadRef
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ""
        major_pattern: "230"
        minor_pattern: "0"
        format: "${major}.${minor}.${patch}-RC${increment}"
        short_tags: false
        bunch_each_commit: true
```
