### ISSUE TITLE
Patch increment is not incrementing

### ISSUE THREAD

**Issue by eliseuborges** [PaulHatch/semantic-version#24]
Hi Guys,

How to increment patch part number? 

I would like to follow semantic version format X.Y.Z without prerelease at my tags name but when I commit my code (with or without (patch) label on message) that just increment prerelease number part and not increment patch part as default.

Is that behavior expected?

This is my action code.
```  
name: CI

on:        
  push:
    branches: [ main ]

jobs:  
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Git Semantic Version
        id: semantic_version
        uses: PaulHatch/semantic-version@v4
        with:
          short_tags: true
          tag_prefix: "v"
          format: "${major}.${minor}.${patch}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.semantic_version.outputs.version }}
          release_name: ${{ steps.semantic_version.outputs.version }}
          draft: false
          prerelease: false
```
