### ISSUE TITLE
Tags without a prefix is not possible

### ISSUE THREAD

**Issue by night0wl** [PaulHatch/semantic-version#30]
In the actions.yaml the input `tag_prefix` is defined as optional, however, a default of "v" is specified.

The behaviour of the actions toolkit (as observed in [this issue](https://github.com/actions/toolkit/issues/272)) is that specifying `tag_prefix: ''` is equivalent to omitting it, and thus "v" is always used.

This clearly is not the expected behaviour as [line 5 of index.js](https://github.com/PaulHatch/semantic-version/blob/master/index.js#L5) checks and expects to be able to define a blank prefix.

Either no default should be defined, or the default should be blank.

**Comment by PaulHatch** [comment]
I read this issue, [yet in a test](https://github.com/PaulHatch/repo-test/actions) I am unable to reproduce this problem--setting `tag_prefix` to an empty string results in a suggested version that does not include the prefix, and the action picks up a tag without a prefix and suggests an incremented tag.

On line 5 of index.js, the `getInput` call will always return a value, so yeah, that `|| ''` isn't really necessary--this logic is actually [already present](https://github.com/PaulHatch/semantic-version/blob/8e992758756c2dae81a746077e54aead5067a825/dist/index.js#L1472) inside the `getInput` implementation in fact.

**Comment by night0wl** [comment]
Interesting. Where are you setting `tag_prefix`? This is the snippet from our workflow YAML file

```
        uses: paulhatch/semantic-version@ed818a75eb51eee5b4072b72a07031cd52a9f09f # Pinned at vetted version 4.0.1
        with:
          tag_prefix: ""
          format: "${major}.${minor}.${patch}"
          short_tags: false
```

This was ignored when running the workflow. We tried with both single and double quotes.

**Comment by PaulHatch** [comment]
Hrm, that's very strange. This was set [the same as your example](https://github.com/PaulHatch/repo-test/blob/master/.github/workflows/run.yaml). I added the `format` and `short_tags` parameters matching your configuration as well and ran a matrix with all Windows and Linux OS just in case and got the [same result](https://github.com/PaulHatch/repo-test/runs/2423369118?check_suite_focus=true#step:3:9). In another test I printed environment variables and did see the INPUT_TAG_PREFIX set to an empty string. I am thinking this could be checked directly by this action as a workaround to the runner issue, but I'd like to replicate the issue first. Reading the GitHub Runner issue it seems more that they can't tell whether an input was set or not as opposed to default values being used when an empty string is provided.

One thing I just noticed is that the log output for the test repo looks like this:

```
Run paulhatch/semantic-version@v4.0.1
  with:
    format: ${major}.${minor}.${patch}
    short_tags: false
    branch: HEAD
    major_pattern: (MAJOR)
    minor_pattern: (MINOR)
    bump_each_commit: false
```

The prefix was set for the action and the result matches what was expected, but I do not see it in the debug information. This is written in the runner [here](https://github.com/actions/runner/blob/main/src/Runner.Worker/Handlers/Handler.cs#L87) and I'd suspect this to be an issue, however on other actions I have, including the workflow for semantic-version itself, that do not set a prefix and instead use the default "v" this [does appear](https://github.com/PaulHatch/semantic-version/runs/2416225809?check_suite_focus=true#step:6:4). Perhaps you could check in your action's log to see if the parameter is present? That's maybe not the full answer but some place to start at least.

A few other things, I noticed when fixing the forward slash prefix issue that there was a console.log(tag) line left in accidentally. I have removed it for the next version, but you can see it [here](https://github.com/PaulHatch/repo-test/runs/2423369118?check_suite_focus=true#step:3:9). This isn't the correct version. Also, this prefix is only used as a convention for tags, and the tag != the semantic version. Kind of going out on a limb here but sometime this trips people up.

It would be helpful if you could share a repo that replicates this issue.

**Comment by night0wl** [comment]
I cannot share a repo I'm afraid, as it is not a public project. However, I have looked back over our Action runs while working on this. Our first idea was to remove the prefix just to see if that worked, so we just remove the line `tag_prefix: "component/"`. So the full YAML for that step looked like:
```
      - name: Create New Tag
        id: newtag
        uses: paulhatch/semantic-version@v4.0.1
        with:
          format: "${major}.${minor}.${patch}"
          short_tags: false
```
The output in the logs was:
```
  with:
    format: ${major}.${minor}.${patch}
    short_tags: false
    branch: HEAD
    tag_prefix: v
    major_pattern: (MAJOR)
    minor_pattern: (MINOR)
    bump_each_commit: false
```
As you can see, we ended up with "v" as the prefix.

**Comment by PaulHatch** [comment]
Right, the default "v" is expected when the prefix is left blank, however if you include the `tag_prefix: ""` line the output should not include `tag_prefix` at all. (This should probably be fixed in the GitHub Actions Runner since the value was in fact specified, but for our purposes should allow tags without prefix.)

It doesn't have to be the same repo, any example that replicates this will work. If you have a look at [PaulHatch/repo-test](https://github.com/PaulHatch/repo-test) I've not been able to replicate. You can fork this repo if you like and show what I'm missing here.

**Comment by night0wl** [comment]
I cannot share the repo unfortunately. However, I can confirm that when we explicitly set `tag_prefix: ""` then we saw:
```
Run paulhatch/semantic-version@v4.0.1
  with:
    format: ${major}.${minor}.${patch}
    short_tags: false
    branch: HEAD
    major_pattern: (MAJOR)
    minor_pattern: (MINOR)
    bump_each_commit: false
```
However, the console.log printed `component/v0.0.1` .. which is quite odd. I think at this point we re-ran jobs and someone did a force push at some point which looks like it might have messed something up. We've moved on from this experiment now so cannot re-run to test again. I'm going to close this as it seems to be a false report. Apologies.
