### ISSUE TITLE
Wrong calculation of the ancestor for implicit patch and increment calculation

### ISSUE THREAD

**Issue by GiuseppeChiesa-TomTom** [PaulHatch/semantic-version#40]
Hello, I'm using this action to tag prereleases versions.

While using it, I've noticed that sometimes the implicit version is not what I'm expecting (patch is not bumped and increments are wrong).
By checking the code it looks like here https://github.com/PaulHatch/semantic-version/blob/00b872db01b3ec5ffbc6b1f20d459fc6af5fe7b1/index.js#L147

the tag is calculated by looking at the immediate previous tag with the semver release format. It seems that there is a problem that arise when there is no matching tag. The returned tag is indeed the second immediate previous tag. 
At least this is what it shows from my experimentation. Also in the git manual is not clear:

_If an exact match was not found, git describe will walk back through the commit history to locate an ancestor commit which has been tagged. The ancestor’s tag will be output along with an abbreviation of the input commit-ish’s SHA-1._ ( https://git-scm.com/docs/git-describe )

In my specific case I have these 2 tags as ancestors (as an example):

HEAD
v0.1.11-prerelease-994f2da
v0.1.10-prerelease-38e0a98

when I run the command (as per code) I get back the second previous immediate tag: 
```
❯ git describe --tags --abbrev=0 --match='v*[0-9].*[0-9].*[0-9]' HEAD~1
v0.1.10-prerelease-38e0a98
```

If instead I extend the match to find the version pattern then I get the proper immediate ancestor:
```
❯ git describe --tags --abbrev=0 --match='v*[0-9].*[0-9].*[0-9]*' HEAD~1              
v0.1.11-prerelease-994f2da

```
Having the wrong ancestor it creates issues in the calculation of patch and increment.

**Comment by datapolitical** [comment]
I'm running into a related issue. After a release the software ignores the release version and tries to calculate the version from the previous release:

So after I released version 3.3.0 (with tag v3.3.0) I get:

Run paulhatch/semantic-version@v3.2
v3.2.4
Version is 3.3.0+2

which causes an error when I try to use it to generate a release because 3.3.0 already exists.

```
      - uses: actions/checkout@v2
        with:
          fetch-depth: zero
          ref: 'main'
      
      # Create Version
      - name: Create Version
        id: create_version
        uses: paulhatch/semantic-version@v3.2
        with:
          # The prefix to use to identify tags
          branch: "main"
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          format: "${major}.${minor}.${patch}"
          # Optional path to check for changes. If any changes are detected in the path the
          # 'changed' output will true. Enter multiple paths separated by spaces.
          # change_path: "src/my-service"
          # Named version, will be used as suffix for name version tag
          # namespace: project-b
          # Indicate whether short tags like 'v1' should be supported. If false only full
          # tags like 'v1.0.0' will be recognized.
          short_tags: true
          # If this is set to true, *every* commit will be treated as a new version.
          bump_each_commit: false
```

**Comment by datapolitical** [comment]
The weird part is that it works fine on every build after the first one. So I just pushed a change and this time I got:

v3.3.0
Version is 3.3.1+2

**Comment by GiuseppeChiesa-TomTom** [comment]
> Hi Giuseppe, So in this case is each commit tagged? Are these tags considered releases?

The idea behind the usage of this action was to have a set of "prerelease" tags between 2 release semver tags.

So the repository would look like (most recent on top):

```
v0.2.2-prerelease-01234
v0.2.1-prerelease-f0123 <- v0.2.1 (release semver tag)
v0.2.0-prerelease-ef012 (semver minor level commit)
v0.1.3-prerelease-def01 <- v0.1.3 (release semver tag)
v0.1.2-prerelease-cdef0 <- v0.1.2 (release semver tag)
v0.1.2-prerelease-bcdef
v0.1.1-prerelease-abcde
v0.1.0 
```

Each release semver tag (performed by another workflow) would make this action reset the counter and subsequently recalculate the tags of the newest PRs merged on main branch.

I'm not using `bump_each_commit` because I would like to ignore changes in some specific path (see configuration below).

Configuration:

```
      - uses: paulhatch/semantic-version@v4.0.2
        id: autotag
        with:
          tag_prefix: "v"
          format: "v${major}.${minor}.${patch}-prerelease-${{ steps.short-sha.outputs.value }}"
          short_tags: false
          # use the pathspec from git: https://github.com/PaulHatch/semantic-version/issues/31
          # when calculating changes, ignore: .github CODEOWNERS
          change_path: '. ":^.github" ":^CODEOWNERS"'
          # https://regex101.com/r/czKGoZ/1
          major_pattern: '/^(\w+(\(\w+\))?(!)+|.*MAJOR|.*BREAKING CHANGE|.*BREAKING-CHANGE):.*/'
          # https://regex101.com/r/WtoGzh/1
          minor_pattern: '/^(feat|perf|refactor|revert|test|MINOR)?(\(\w+\))?:.*/'
```

Is this possibility pursuable with this action?
