### ISSUE TITLE
Need Help: No names found, cannot describe anything

### ISSUE THREAD

**Issue by kwang7nyc** [PaulHatch/semantic-version#41]
It shows me error in github actions:

> The command 'git describe --tags --abbrev=0 --match=v*[0-9.] e8fa879ba5cdbba7dda05effdc973bbc62e9660d~1' failed: Error: The process '/usr/bin/git' failed with exit code 128
> stderr: fatal: No names found, cannot describe anything.

Here's my setup

```
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.9.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.7"

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          bump_each_commit: true
```
