### ISSUE TITLE
Docs on interacting calculated vars

### ISSUE THREAD

**Issue by karlschriek** [PaulHatch/semantic-version#42]
Really nice GitHub Action. Could you add some docs on interacting with it as one step in a larger job?

For example, a typical use-case might be to create the semantic version followed by building an pushing a Docker image with the same tag, something like:

```
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: paulhatch/semantic-version@v4.0.2
        id: semantic_version
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          ...etc.
                
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/myorg/my-image:${{ steps.semantic_version.outputs.VERSION }}
```

I'm sure this must be possible but I haven't been able to figure out exactly how
