### ISSUE TITLE
Reference version as a parmater for deployments?

### ISSUE THREAD

**Issue by mikeestrada** [PaulHatch/semantic-version#45]
Hello, I am looking to learn if we can reference the generated version number elsewhere in the yaml files.

**Comment by PaulHatch** [comment]
If I understand you correctly the yaml file you're referring to is theGitHub Actions workflow definition, so you mean reference the version in other steps of the build?

If so, yes, the outputs are described [here in the readme](https://github.com/PaulHatch/semantic-version#outputs).

To use them in another step, you can add them using a reference wrapping `steps.{id of version action}.outputs.{output field}` in `${{}}` in the yaml file, like this example that uses `version` and `increment`:

```
...
      - name: Version
        id: version
        uses: paulhatch/semantic-version@v4.0.3
      - name: Some Actions
        run: ./do-something.sh
        env:
          VERSION: ${{ steps.version.outputs.version }}.${{ steps.version.outputs.increment }}
```
