### ISSUE TITLE
Consistently getting a No Tags warning that is leading to the same tag

### ISSUE THREAD

**Issue by Katellification** [PaulHatch/semantic-version#55]
Consistently getting this warning:

```text
Warning: No tags are present for this repository. If this is unexpected, check to ensure that tags have been pulled from the remote.
Version is 0.0.1
```

This leads to the same version tag being produced over and over. Only if the last commit includes the `(MAJOR)` or `(MINOR)` keyword does it produce `1.0.0` or `0.1.0` instead, but will immediately produce `0.0.1` with a subsequent PR.

We work using a fork workflow, and I have made sure that we fetch the tags from upstream:

```text
git fetch --all --tags
```

This had no effect on the results.

Here is my workflow:

```yaml
name: Repo Semantic Versioning

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Increment Semantic Version
        id: git_semantic_version
        uses: PaulHatch/semantic-version@v5.0.0-alpha2
        with:
          # Set to specify a specific branch, default is the current HEAD
          branch: HEAD
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a major (breaking) change. Wrap with '/' to match using a regular expression.
          major_pattern: "(MAJOR)"
          # A string which, if present in a git commit, indicates that a change represents a minor (feature) change. Wrap with '/' to match using a regular expression.
          minor_pattern: "(MINOR)"
          # Pattern to use when formatting output version
          version_format: "${major}.${minor}.${patch}"
          # If true, every commit will be treated as a bump to the version.
          bump_each_commit: false
          # If true, the body of commits will also be searched for major/minor patterns to determine the version type.
          search_commit_body: true
          # The output method used to generate list of users, 'csv' or 'json'. Default is 'csv'.
          user_format_type: json
```

Have I misunderstood one of the parameters and set something up incorrectly here? 
Thanks
