### ISSUE TITLE
change_path does not work

### ISSUE THREAD

**Issue by ianbondoc** [PaulHatch/semantic-version#57]
Given the following workflow:

```
name: "CI"
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 20
      - name: App Release
        id: app-version
        uses: paulhatch/semantic-version@v4.0.3
        with:
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          change_path: "src/app"
          search_commit_body: true
      - name: DB Release
        id: db-version
        uses: paulhatch/semantic-version@v4.0.3
        with:
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          change_path: "src/database"
          namespace: db
          search_commit_body: true
      - name: Github Release
        run: |
          echo "App Version: ${{steps.app-version.outputs.version}}"
          echo "App Tag: ${{steps.app-version.outputs.version_tag}}"
          echo "App Changed: ${{steps.app-version.outputs.changed}}"
          echo "App Authors: ${{steps.app-version.outputs.authors}}"
          echo "DB Version: ${{steps.db-version.outputs.version}}"
          echo "DB Tag: ${{steps.db-version.outputs.version_tag}}"
          echo "DB Changed: ${{steps.db-version.outputs.changed}}"
          echo "DB Authors: ${{steps.db-version.outputs.authors}}"
```

when i change the file in the src/database directory only with the following comment:

```
feat: some change

BREAKING CHANGE: just a test
```

then the db major version should be bumped up and the changed flag for app is false

but what i get in the logs is:

![image](https://user-images.githubusercontent.com/74332141/182168650-20fba3d0-373d-4164-9447-0476010f3876.png)
 
note that the "changed" output is always "true"

**Comment by ianbondoc** [comment]
correction, it seems it's the search_commit_body is the one that is not supported
![image](https://user-images.githubusercontent.com/74332141/182251479-719c0c98-3398-4453-90d5-d109559e85fd.png)

**Comment by PaulHatch** [comment]
Hey @ianbondoc, thanks for this report, I have been traveling and have not had a chance to look at this until today, but in the meantime you might consider using the latest version, [5.0.0-alpha2](https://github.com/PaulHatch/semantic-version/releases/tag/v5.0.0-alpha2), which I am planning to release as GA within the next week or so.

Version 5.0.0 is basically a from scratch re-write in TypeScript, so in any case I'd say it is less likely to have the same issues as previous versions.

**Comment by ChrisOwenBoring** [comment]
I can confirm that even on 5.0.0-alpha2 this doesn't appear to work.

**Comment by PaulHatch** [comment]
Closing. I have not been able to reproduce this for any version of this action, for example using the latest:

```
      - uses: paulhatch/semantic-version@v5.0.0
        id: version
        with:
          change_path: "project/path"
      - name: "Output changed status"
        run: echo "${{ steps.version.outputs.changed }}"
```

Outputs true when a commit modifies a file in the change path like `project/path/test.txt` and false when a change does not.

If anyone is still having trouble, see [the getting help section of the contributing doc](https://github.com/PaulHatch/semantic-version/blob/master/contributing.md#getting-help) for information about how to provide a test case or sample and open a new ticket.
