### ISSUE TITLE
Release tag isn't automatically created

### ISSUE THREAD

**Issue by Roms1383** [PaulHatch/semantic-version#58]
Hello and thanks for this github action, it's very convenient and customizable.
I have just one question, as I am not sure it's the expected behaviour, some misconfiguration of mine, or maybe a bug.
<details><summary>given this release workflow (click to see details)</summary>

```yaml
name: Release
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: 
      - completed

jobs:
  tag:
    name: Semantic versioning
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Automatically tag next version
        uses: paulhatch/semantic-version@v5.0.0-alpha2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          bump_each_commit: false
          search_commit_body: true
          user_format_type: "csv"
```

</details>

the workflow gets correctly triggered, and runs smoothly, calculating the next version correctly.
However it doesn't push the guessed tag directly, instead in the CI it pops a link redirecting me to do so :
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/21016014/183346713-1554e4a7-523f-44b2-91b9-4faf898394ef.png">
Is this the expected behaviour ? My assumption was that this action would automatically create it without any prompt.
Thanks in advance for the clarification :)
