### ISSUE TITLE
Exception thrown if namespace contains a `/` character

### ISSUE THREAD

**Issue by rvodden** [PaulHatch/semantic-version#61]
Configure a github action with the following step:
```
      uses: paulhatch/semantic-version@v4.0.3
      id: semantic_namespaced
      with:
        namespace: infrasturcture/namespace
        tag_prefix: "v"
        major_pattern: "BREAKING"
        minor_pattern: "feat"
```

Expected behavior:

A tag similar to `v0.1.0-infrastructure/network` is applied to the commit

Observed behaviour:

an invalid tag exception is thrown: `Error: Invalid tag v0.1.0-infrastructure/network ()`
