### ISSUE TITLE
No tags are present for this repository

### ISSUE THREAD

**Issue by avoca999** [PaulHatch/semantic-version#63]
I'm sure I'm doing something wrong, but not sure what. I'm getting this error:

`Warning: No tags are present for this repository. If this is unexpected, check to ensure that tags have been pulled from the remote.`

This is my setup:
```
write-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
        # so it gets tags
    
    - uses: paulhatch/semantic-version@v5.0.0-alpha2
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
        namespace: scratch
        bump_each_commit: false
        search_commit_body: false
        user_format_type: "csv"
```
and the output is:
```
Warning: No tags are present for this repository. If this is unexpected, check to ensure that tags have been pulled from the remote.
Version is 0.1.0-prerelease7
To create a release for this version, go to https://github.com/avoca999/scratch/releases/new?tag=v0.1.0-scratch&target=ce9293254a1cf[13](https://github.com/avoca999/scratch/runs/8271206435?check_suite_focus=true#step:3:14)eb766bf53f1a63749282b95d0
```
I can see tags by running:
```
 listTags:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_tags
        with:
          route: GET /repos/avoca999/scratch/git/matching-refs/tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo tags: ${{ steps.get_tags.outputs.data }}"
```
which produces:
```
echo tags: [
    {
      "ref": "refs/tags/0.0.1-prerelease24",
      "node_id": "REF_kwDOH9CirLxyZWZzL[3](https://github.com/avoca999/scratch/runs/8271206023?check_suite_focus=true#step:3:3)RhZ3MvMC4wLjEtcHJlcmVsZWFzZTI0",
      "url": "https://api.github.com/repos/avoca999/scratch/git/refs/tags/0.0.1-prerelease24",
      "object": {
        "sha": "6bf2f20472c705ffa13e0e2d805c8064f9945df1",
        "type": "commit",
        "url": "https://api.github.com/repos/avoca999/scratch/git/commits/6bf2f20472c705ffa13e0e2d805c8064f9945df1"
      }
    },
    {
      "ref": "refs/tags/0.1.0",
      "node_id": "REF_kwDOH9CirK9yZWZzL3RhZ3MvMC[4](https://github.com/avoca999/scratch/runs/8271206023?check_suite_focus=true#step:3:4)xLjA",
      "url": "https://api.github.com/repos/avoca999/scratch/git/refs/tags/0.1.0",
      "object": {
        "sha": "d9aa7cb6cc0438fabcec[5](https://github.com/avoca999/scratch/runs/8271206023?check_suite_focus=true#step:3:5)e4deb1f8ebe0[6](https://github.com/avoca999/scratch/runs/8271206023?check_suite_focus=true#step:3:6)5db7d1",
        "type": "commit",
        "url": "https://api.github.com/repos/avoca999/scratch/git/commits/d9aa[7](https://github.com/avoca999/scratch/runs/8271206023?check_suite_focus=true#step:3:7)cb6cc043[8](https://github.com/avoca999/scratch/runs/8271206023?check_suite_focus=true#step:3:8)fabcec5e4deb1f8ebe065db7d1"
      }
    }
  ]
```
Any pointers gratefully received!

**Comment by PaulHatch** [comment]
Since the parameter `tag_prefix` is `v` it is looking for tags like `v1.0.0`, if you want to use this `0.1.0` style, set the `tag_prefix` to an empty string.

**Comment by avoca999** [comment]
Agh, of course! Thanks - but I've updated (to the v- style) and I'm getting the same thing:

Updated workflow:
 ```
 write-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
        # so it gets tags
    
    - uses: paulhatch/semantic-version@v5.0.0-alpha2
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "v${major}.${minor}.${patch}-prerelease${increment}"
        namespace: scratch
        bump_each_commit: false
        search_commit_body: false
        user_format_type: "csv"
```
I see the tags (incl new v- tag) in the checkout:
```
  Resolving deltas: 100% (36/36), done.
  From https://github.com/avoca999/scratch
   * [new branch]      master             -> origin/master
   * [new tag]         0.0.1-prerelease24 -> 0.0.1-prerelease24
   * [new tag]         0.1.0              -> 0.1.0
   * [new tag]         0.2.0              -> 0.2.0
   * [new tag]         v0.3.0             -> v0.3.0
  /usr/bin/git branch --list --remote origin/master
    origin/master
  /usr/bin/git rev-parse refs/remotes/origin/master
```
but then still get:
```
Run paulhatch/semantic-version@v5.0.0-alpha[2](https://github.com/avoca999/scratch/runs/8273216431?check_suite_focus=true#step:3:2)
  with:
    tag_prefix: v
    major_pattern: (MAJOR)
    minor_pattern: (MINOR)
    version_format: v${major}.${minor}.${patch}-prerelease${increment}
    namespace: scratch
    bump_each_commit: false
    search_commit_body: false
    user_format_type: csv
    branch: HEAD
Warning: No tags are present for this repository. If this is unexpected, check to ensure that tags have been pulled from the remote.
Version is v0.1.0-prerelease1[3](https://github.com/avoca999/scratch/runs/8273216431?check_suite_focus=true#step:3:3)
To create a release for this version, go to https://github.com/avoca999/scratch/releases/new?tag=v0.1.0-scratch&target=bda1725[4](https://github.com/avoca999/scratch/runs/8273216431?check_suite_focus=true#step:3:4)d1fe694d6f92ece403fd2f368[5](https://github.com/avoca999/scratch/runs/8273216431?check_suite_focus=true#step:3:5)[12](https://github.com/avoca999/scratch/runs/8273216431?check_suite_focus=true#step:3:13)441f
```
Thanks!
