### ISSUE TITLE
Error when when two workflows are running simultaneously

### ISSUE THREAD

**Issue by eliseuborges** [PaulHatch/semantic-version#8]
When two workflows are running simultaneously, the last one retrieve a version number that was already generated by the first one. Is there any solution for this problem? This a peace of my action .yml
```
release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend, tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Git Semantic Version
        id: semantic_version
        uses: PaulHatch/semantic-version@v3.1.2
        with:
          tag_prefix: "v"
          format: "v${major}.${minor}.${patch}"      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.semantic_version.outputs.version }}
          release_name: ${{ steps.semantic_version.outputs.version }}
          draft: false
          prerelease: false
```
