### ISSUE TITLE
Tagging Containers using this Action

### ISSUE THREAD

**Issue by bpmooch** [PaulHatch/semantic-version#82]
How do I modify the following job to tag the container as the computed semver? Is there a value I can replace `github.sha` with?

```
  deploy:
    name: Promote
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Github Tag Increment
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          change_path: "forklift"
          major_pattern: "(FORKLIFT_MAJOR)"
          minor_pattern: "(FORKLIFT_MINOR)"
          namespace: forklift
      - name: Re-Tag Container
        run: |
          skopeo login --username ${{ secrets.AZURE_CR_USER }} \
            --password ${{ secrets.AZURE_CR_PW }} ${{ secrets.AZURE_CR }} \
            && skopeo copy docker://${{ secrets.AZURE_CR }}/forklift:${{ github.sha }} \
            docker://${{ secrets.AZURE_CR }}/forklift:latest
```
