### ISSUE TITLE
v5.0.x computes very different version compared to v4

### ISSUE THREAD

**Issue by belcher-rok** [PaulHatch/semantic-version#84]
After updating to v5.0.1, the Action computes a very different version number.

For example, v5.0.1 computes the next version as `2.1.0-development.90`, whereas v4.0.3 computes the next version as `2.2.25-development.4`.

Our workflow looks like this:
```yaml
      - name: Determine next tag (production)
        if: env.EnvironmentName == 'production'
        id: next_tag_prod
        uses: paulhatch/semantic-version@v5.0.1
        with:
          tag_prefix: ""
          version_format: "${major}.${minor}.${patch}"

      - name: Determine next tag (non-prod)
        if: env.EnvironmentName != 'production'
        id: next_tag_nonprod
        uses: paulhatch/semantic-version@v5.0.1
        with:
          tag_prefix: ""
          version_format: "${major}.${minor}.${patch}-${{ env.EnvironmentName }}.${increment}"
```
----
When I run `git for-each-ref` I see these version tags, many of which were created using v4.0.3:
```txt
$ git for-each-ref --sort=-v:*refname --format="%(refname:short)" --merged=HEAD refs/tags/*[0-9].*[0-9].*[0-9]
2.2.24-development.1
2.2.23-development.4
2.2.22-development.4
2.2.21-development.2
...
2.1.1-development.65
2.1.0-prerelease.1
2.1.0-prerelease.0
2.1.0-development.0
2.0.5
2.0.4
2.0.3
2.0.2
...
```

v5.0.x appears to be using the `2.0.5` tag as the "last release" and is ignoring all the intermediate tags. I'm not sure if this is intentional or not. If so, then perhaps it should also apply **all** the intermediate version bumps, not just the first one. Whatever the case, we are stuck on v4.0.3 for the time being.

Thanks! Let me know if I can provide any extra info or help debug.
