### ISSUE TITLE
`fetch-depth` option seems wrong in README - Unexpected input(s) 'fetch-depth', valid inputs are ['branch', 'tag_prefix', 'major_pattern', 'minor_pattern', 'format', 'change_path', 'namespace']

### ISSUE THREAD

**Issue by Vadorequest** [PaulHatch/semantic-version#9]
Seen at https://github.com/UnlyEd/github-action-await-vercel/actions/runs/431379916

![image](https://user-images.githubusercontent.com/3807458/102664239-9c5fa580-4182-11eb-8719-6fcefd8569a5.png)

[Workflow](https://github.com/UnlyEd/github-action-await-vercel/blob/1324d77d0a1b6348a4d4032aa13e50b8af812a4e/.github/workflows/auto-versioning.yml): 
```yml
# Summary:
# Automatically increase the version using semantic versioning
#
# See https://github.com/PaulHatch/semantic-version https://github.com/PaulHatch/semantic-version/tree/v3.1.2

name: 'Auto version increment'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - '*' # XXX for testing

jobs:
  run-semantic-versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: paulhatch/semantic-version@v3.1.2
        with:
          fetch-depth: 0
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a major (breaking) change
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          format: "${major}.${minor}.${patch}-prerelease.${increment}"

```

**Comment by Vadorequest** [comment]
Oh, I get it. You used `fetch-depth` instead of `fetch_depth` (underscore)

**Comment by Vadorequest** [comment]
But doesn't seem right either. See https://github.com/UnlyEd/github-action-await-vercel/actions/runs/431408935

![image](https://user-images.githubusercontent.com/3807458/102664811-e1d0a280-4183-11eb-85ce-0c4d64b43e20.png)

**Comment by Vadorequest** [comment]
Arf. My bad, I applied it to the wrong action. Here's what I should have done:

```yml
jobs:
  run-semantic-versioning:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See https://github.com/PaulHatch/semantic-version#important-note-regarding-the-checkout-action
      - uses: paulhatch/semantic-version@v3.1.2
        with: # See https://github.com/PaulHatch/semantic-version#usage
          tag_prefix: "v" # The prefix to use to identify tags
          major_pattern: "(MAJOR)" # A string which, if present in a git commit, indicates that a change represents a major (breaking) change
          minor_pattern: "(MINOR)" # Same as above except indicating a minor change
          format: "${major}.${minor}.${patch}-prerelease.${increment}" # A string to determine the format of the version output

```
